services:
    app:
        container_name: CSErver
        restart: always
        build:
            context: ./app
            args:
                SECRET: $SECRET
                MYSQL_BASE_PASS: $MYSQL_BASE_PASS
                MYSQL_GAME_PASS: $MYSQL_GAME_PASS

        networks:
            - net

    nginx:
        container_name: Nginx
        restart: always
        build:
            context: ./nginx
        
        networks:
            - net
        ports:
            - "80:80"
    
    mysql:
        container_name: DB
        environment:
            - MYSQL_ROOT_PASSWORD
        build:
            context: ./mysql
            args:
                MYSQL_BASE_PASS: $MYSQL_BASE_PASS
                MYSQL_GAME_PASS: $MYSQL_GAME_PASS
            
        volumes: #For persistent storage
            - mysql_volume:/var/lib/mysql
        networks:
            - net

volumes:
    mysql_volume:

networks:
    net: